### ISSUE TITLE
Failed to execute script main

### ISSUE THREAD

**Issue by AbjectLlama** [ImaniiTy/GreenLuma-Reborn-Manager#13]
This just started happening, so i'm thinking it's on my end but here is the log
[errors.log](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/3388369/errors.log)

**Comment by ImaniiTy** [comment]
idk what causes this bug but for some reason, the program randomly requires admin privileges to run, I think it's a Windows issue but who knows...

For now, renaming the folder where the program is fixes this problem.

**Comment by AbjectLlama** [comment]
Thanks ;)
