### ISSUE TITLE
Straight up won't execute

### ISSUE THREAD

**Issue by thenewstuff** [ImaniiTy/GreenLuma-Reborn-Manager#18]
[errors.log](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/3914430/errors.log)
I don't even know what's wrong

**Comment by ImaniiTy** [comment]
maybe its to late but you dont have the file "DllInjector.ini" in the steam folder, try reinstalling GL

**Comment by thenewstuff** [comment]
Greenluma died bro :(

**Comment by ImaniiTy** [comment]
What you mean? It just moved to a new thread and is still getting updated
https://cs.rin.ru/forum/viewtopic.php?f=29&t=103709

**Comment by thenewstuff** [comment]
Fr? I red a few days ago in the forum that ir wasnt working anymore due to
a steam security patch

**Comment by ImaniiTy** [comment]
I used it last weekend without any problem
