### ISSUE TITLE
Hi ,Manager crashes after pressing "Run GLR" button

### ISSUE THREAD

**Issue by sphere1001** [ImaniiTy/GreenLuma-Reborn-Manager#19]
the Manager runs with Steamdb.info now after installing OpenSSL, but it crashes after pressing the button. Any ideas ?

**Comment by sphere1001** [comment]
Hi ,now I get this far that it shows me this cmd.exe 
![steam](https://user-images.githubusercontent.com/5193569/74483292-7f00e180-4eb6-11ea-8142-570df31705c1.PNG)

I guess I have to configure DllInject.ini somewhow ?

**Comment by ImaniiTy** [comment]
Are you using the latest version of Greenluma i.e., Greenluma2020?

**Comment by sphere1001** [comment]
No, but,where can I get from ?

Thank you for your reply.

**Comment by ImaniiTy** [comment]
here https://cs.rin.ru/forum/viewtopic.php?f=29&t=103709.

You're welcome.

**Comment by sphere1001** [comment]
thank you very much.
I will test it and tell you how it went..

**Comment by sphere1001** [comment]
I have tested it with GLR 2020 ,but it gives me same errors.
Actually I cannot see the games added to the account.
Could you provide me another advice ?

**Comment by ImaniiTy** [comment]
Can you upload the *.log files in the app folder? Im not home right now but i'll look it tonight

**Comment by sphere1001** [comment]
that's great ,thank you, I will upload them here.
[appinfo_log.txt](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/4221077/appinfo_log.txt)
[bootstrap_log.txt](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/4221078/bootstrap_log.txt)
[cef_log.previous.txt](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/4221079/cef_log.previous.txt)
[cef_log.txt](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/4221080/cef_log.txt)
[cloud_log.txt](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/4221081/cloud_log.txt)
[compat_log.txt](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/4221082/compat_log.txt)
[configstore_log.txt](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/4221083/configstore_log.txt)
[connection_log.txt](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/4221084/connection_log.txt)
[content_log.txt](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/4221085/content_log.txt)
[controller.txt](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/4221086/controller.txt)
[controller_ui.txt](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/4221087/controller_ui.txt)
[librarysharing_log.txt](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/4221088/librarysharing_log.txt)
[parental_log.txt](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/4221089/parental_log.txt)
[remote_connections.txt](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/4221090/remote_connections.txt)
[shader_log.txt](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/4221091/shader_log.txt)
[sitelicense_log.txt](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/4221092/sitelicense_log.txt)
[stats_log.txt](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/4221093/stats_log.txt)
[workshop_log.txt](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/4221094/workshop_log.txt)

I do hope there are not too many of them, but I trust in that you know where to search for.

**Comment by ImaniiTy** [comment]
Lol i mean the *.log's in my program folder

**Comment by ImaniiTy** [comment]
But i think the problem isn't my app, if it runs well you should try to ask for help on the GreenLuma2020 post

**Comment by sphere1001** [comment]
Hi ImaniiTy,
I have succefully added some dlcs of my games to Steam with GreenLuma Manager.
I still have got a question.
Can we make apps which we have not bought ,appear in Steam through GreenLuma ?

**Comment by ImaniiTy** [comment]
You can add games you don't own with GL but you wont be able to download it through steam, you'll need to get the files elsewhere

**Comment by sphere1001** [comment]
oh ok, thank you

**Comment by sphere1001** [comment]
Well another question..
How would you go about it to add these games you do not own ?
