### ISSUE TITLE
Cannot connect to steam DB after GLR manager update

### ISSUE THREAD

**Issue by Santicx** [ImaniiTy/GreenLuma-Reborn-Manager#20]
So I am having this issue where I want to add DLC/game to  Green Luma manager the app says cannot connect to steamDB. There was already an issue about that and tried installing OpenSSL and still doesn't work.

**Comment by dahcat1** [comment]
Yeah me too, guess we are gonna have to wait for an update

**Comment by ImaniiTy** [comment]
this new update should fix the issue
