### ISSUE TITLE
Crash on search

### ISSUE THREAD

**Issue by JotaroKujo123** [ImaniiTy/GreenLuma-Reborn-Manager#23]
Hi i got the program to connect to the steamdb but now when i try and search for anything it stays on "Searching..." for a few seconds and then crashes. I have provided the error log file if you could take a look at it and help me resolve this. Any help is much appreciated!
[errors.log](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/4580299/errors.log)

**Comment by WeeabooGod** [comment]
This was 14 days ago. If you are still having problems, or if anyone else is having problems. OpenSLL has updated to 1.1.1g (I was on 1.1.1f experiencing the crashing).

Update/Reinstall OpenSLL and it might stop crashing.

**Comment by niracheta** [comment]
i have the same error log and just installed openSLL, any other options?

**Comment by ImaniiTy** [comment]
this new update should fix the issue
