### ISSUE TITLE
Can't connect to Steamdb in GreenLuma Reborn Manager

### ISSUE THREAD

**Issue by MaksInTheSky** [ImaniiTy/GreenLuma-Reborn-Manager#29]
I can't connect to steamdb, when I search for a game / DLC, I get a message
![Image](https://user-images.githubusercontent.com/67097091/104814097-15075f80-581e-11eb-9a08-d01ff32ede72.jpg)

**Comment by AI38549582-54ad-4197-8ac2-01b9acd8c1fd** [comment]
see Pinned Issue https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/issues/10

**Comment by ImaniiTy** [comment]
this new update should fix the issue
