### ISSUE TITLE
New update released

### ISSUE THREAD

**Issue by Rogus** [ImaniiTy/GreenLuma-Reborn-Manager#3]
Steam006 released a new update with a rework of the parameters of the legit stealth mode (Steam)
Legit stealth mode (Steam):
1. Copy GreenLuma_Reborn_x86.dll, DLLInjector.exe and DllInjector.ini to your Steam folder.
2. Make a shortcut to DLLInjector.exe and add "-DisablePreferSystem32Images -CreateFile1 NoHook.bin" as parameters.
3. Open DllInjector.ini and replace the exe line with the NoHook one.
4. Start Steam with the shortcut.

**Comment by Rogus** [comment]
https://cs.rin.ru/forum/viewtopic.php?f=29&t=80797&start=1879

**Comment by ImaniiTy** [comment]
Done hehe
