### ISSUE TITLE
Can't create new profile

### ISSUE THREAD

**Issue by pitrako** [ImaniiTy/GreenLuma-Reborn-Manager#5]
Can't make custom profiles, the program closes itself, can only use default profile.

**Comment by ImaniiTy** [comment]
Hum... Try to go here:  `C:\Users\YOUR_USERNAME\AppData\Local\GLR_Manager`
or just paste `%localappdata%/GLR_Manager` on the folder address bar like this:
![Alt Text](https://i.imgur.com/P4N7Fl9.png)

and delete everything inside it, or just delete the folder itself but before you do it can you please zip the folder and upload here so i can see what went wrong?

If the error persist i'm uploading a new version of the program with a crash log and you can send me this log instead

**Comment by ImaniiTy** [comment]
And the `GLR_Manager` folder would be useful too(just zip it to send here)

**Comment by ImaniiTy** [comment]
Fixed on the next version it was a silly mistake, sorry for the inconvinience
