### ISSUE TITLE
Not opening! error!

### ISSUE THREAD

**Issue by Mechanical-sanity** [ImaniiTy/GreenLuma-Reborn-Manager#6]
When i try to open the app, the message "failed to execute script main" appears. All i did was extract the files and clicked on the .exe file. is there any way for this to work? Also, will this work for games like half life or Garry's mod? The program, I mean

**Comment by ImaniiTy** [comment]
can you upload the `crash.log` file or just copy and paste it here please? And about the second question, yes these games work and you can even create a cracked dedicated server for those games:
![Alt Text](https://i.imgur.com/CPr7MeT.png)

but if you have any other question about which game work or not try to check the [original post](https://cs.rin.ru/forum/viewtopic.php?f=29&t=80797) 'cause my program is just a wrapper of the GreenLuma Reborn.

**Comment by Mechanical-sanity** [comment]
I forgot to mention that I dont have greenluma reborn by steam006. For some reason, I cant login the site to download it. Can you package it with glr manager? Also, there is no crash log

**Comment by ImaniiTy** [comment]
> there is no crash log

Strange... You downloaded latest release? v1.3.2?

> Can you package it with glr manager?

i don't have permission to do that, you'll need to solve this by yourself sorry.

**Comment by ImaniiTy** [comment]
Actually if you have any way to direct message you i can send you the files

**Comment by Mechanical-sanity** [comment]
I have twitter

**Comment by wackoamd1** [comment]
i have the same problem already tried 1.3.1 AND 1.3.2 with reborn 1.7.0. 
by itself reborn works perfect so thats not the problem , its  just trhe manager that doesnt want to open
