### ISSUE TITLE
Games download and usage. Help!

### ISSUE THREAD

**Issue by Mechanical-sanity** [ImaniiTy/GreenLuma-Reborn-Manager#7]
So I got glr and installed it according to the instructions for steam non lite version, and it said that it did not inject. Glr appeared to work for steam lite, but whenever I try to launch the game, it says that I need to update the game, regardless if I installed the update or not. Can somebody post a full guide on how to install glr for both steam and steam lite and how to get games? I'm so lost

**Comment by Mechanical-sanity** [comment]
Is it because I need an older version of steam? Anybody have an answer? I have downloaded garrys mod through the steam lite method, but it wont open. Can you give me a detailed text explaining what to do to get games?

**Comment by ImaniiTy** [comment]
idk much about steam lite sorry, and as i said you will have more chance of being helped on the forum

**Comment by ImaniiTy** [comment]
maybe this can help:
![Alt Text](https://i.imgur.com/QprWt5R.png)

**Comment by Mechanical-sanity** [comment]
never mind. I fixed everything. Buyt for some reason, your app keeps crashing when I try to run glr through your app. Is there a fix for this?
