### ISSUE TITLE
not opening

### ISSUE THREAD

**Issue by wackoamd1** [ImaniiTy/GreenLuma-Reborn-Manager#8]
failed to execute script main error
already tried 1.3.1 AND 1.3.2 with reborn 1.7.0.
by itself reborn works perfect so thats not the problem , its just the manager that doesnt want to open
and i couldnt find the suloution in the closed issue all it says its solved with no explanation

> there is no crash log

Strange... Did you download the latest release? v1.3.2?

> Can you package it with glr manager?

i don't have permission to do that, you'll need to solve this by yourself sorry.

_Originally posted by @ImaniiTy in https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/issues/6#issuecomment-487813650_

**Comment by ImaniiTy** [comment]
So no crash log in you case too? And Idk how he solved it either

**Comment by wackoamd1** [comment]
nope it just says "failed to execute script main" in a popup , u can click ok and thats it . i even editited the json to manualy put in the steam path. 
could it be that the manager looks for the standard steam path under program files...........etc.. and doesnt find GLR or something cause my steam isnt under the standard path..
just trying to think with u what could be wrong

**Comment by ImaniiTy** [comment]
so the GLR_Manager folder is generated? Can you zip it and send here?

**Comment by ImaniiTy** [comment]
I think i found the problem... I'm handling corrupted profiles but not corrupted configs. And my logging is just broken hehe

**Comment by wackoamd1** [comment]
> so the GLR_Manager folder is generated? Can you zip it and send here?

yes it does create the glr_manager folder under user appdata .........etc.. there is a empty profile folder under it and a config.json with 5 lines in it

**Comment by ImaniiTy** [comment]
change this line
>"steam_path": "f:\Steam"

to this:
> "steam_path": "f:\\\Steam"

**Comment by wackoamd1** [comment]
changed it and still get the same error ;-(

**Comment by wackoamd1** [comment]
> changed it and still get the same error ;-(
> 
> :edit
> moved the GLR_manager folder away ,start GRM it creates a new GLR_manager folder but still throws the error

with the exact same empty profile folder and the exact same config.json

**Comment by ImaniiTy** [comment]
download the latest version, i fucked up the v1.3.2

**Comment by wackoamd1** [comment]
hahahah

**Comment by wackoamd1** [comment]
u are awesome , i dont know what u changed but it works now

**Comment by ImaniiTy** [comment]
on the v1.3.2 i changed some parts of the code but forgot to change one part to work with the new changes(sorry if the explanation sucks i'm still learning english)

**Comment by ImaniiTy** [comment]
Anyway, thanks for the feedback ❤️  and sorry for the inconvenience
